# Configure the analyzer for static analysis of Dart code.
#
# Add the following to pubspec.yaml:
#
#   dev_dependencies:
#     very_good_analysis: ^9.0.0
#
# Invoke the analyzer from the command line:
#
#   flutter analyze

# Activate very_good_analysis lints for comprehensive code quality checks
# designed to enforce high standards and best practices.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    directives_ordering: false

# Identify directories to ignore.

analyzer:
  exclude:
    - ignore/**
    - ignore/
